// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using freshcrumbs.CRM.infrastructure.data;

#nullable disable

namespace freshcrumbs.CRM.infrastructure.Migrations
{
    [DbContext(typeof(MasterCrmDbContext))]
    partial class MasterCrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderKey")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ContactNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("TenantId")
                    .HasColumnType("int");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.HasIndex("TenantId");

                b.ToTable("AspNetUsers", (string)null);
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.Company", b =>
            {
                b.Property<int>("CompanyId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                b.Property<string>("BusinessAddress")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<string>("CompanyCode")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("CompanyName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ContactNo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("CompanyId");

                b.HasIndex("CompanyCode")
                    .IsUnique();

                b.ToTable("Companies");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.CompanyDatabase", b =>
            {
                b.Property<int>("CompanyDatabaseId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyDatabaseId"));

                b.Property<int>("CompanyId")
                    .HasColumnType("int");

                b.Property<string>("CredentialKey")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DatabaseName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("ServerName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("CompanyDatabaseId");

                b.HasIndex("CompanyId");

                b.ToTable("CompanyDatabases");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.Plan", b =>
            {
                b.Property<int>("PlanId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                b.Property<bool>("BranchingEnabled")
                    .HasColumnType("bit");

                b.Property<string>("BillingCycle")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<int?>("MaxBranches")
                    .HasColumnType("int");

                b.Property<int>("MaxUsers")
                    .HasColumnType("int");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("PlanId");

                b.HasIndex("PlanCode")
                    .IsUnique();

                b.ToTable("Plans", t =>
                {
                    t.HasCheckConstraint("CK_Plans_Branching", "([BranchingEnabled] = 1 AND [MaxBranches] >= 1) OR ([BranchingEnabled] = 0 AND [MaxBranches] IS NULL)");

                    t.HasCheckConstraint("CK_Plans_MaxUsers", "[MaxUsers] >= 1");

                    t.HasCheckConstraint("CK_Plans_Price", "[Price] >= 0");
                });
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.PlanFeature", b =>
            {
                b.Property<int>("PlanId")
                    .HasColumnType("int");

                b.Property<string>("FeatureKey")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("PlanId", "FeatureKey");

                b.ToTable("PlanFeatures");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.Subscription", b =>
            {
                b.Property<int>("SubscriptionId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                b.Property<string>("BillingCycle")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<bool>("BranchingEnabled")
                    .HasColumnType("bit");

                b.Property<string>("ChangeType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("ChangedBy")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<int>("CompanyId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Features")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<int?>("MaxBranches")
                    .HasColumnType("int");

                b.Property<int>("MaxUsers")
                    .HasColumnType("int");

                b.Property<int>("PlanId")
                    .HasColumnType("int");

                b.Property<string>("PlanCode")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("PlanName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("PreviousSubscriptionId")
                    .HasColumnType("int");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Reason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("SubscriptionId");

                b.HasIndex("PlanId");

                b.HasIndex("PreviousSubscriptionId");

                b.HasIndex("CompanyId", "StartDate");

                b.ToTable("Subscriptions", t =>
                {
                    t.HasCheckConstraint("CK_Subscriptions_Branching", "([BranchingEnabled] = 1 AND [MaxBranches] >= 1) OR ([BranchingEnabled] = 0 AND [MaxBranches] IS NULL)");

                    t.HasCheckConstraint("CK_Subscriptions_Dates", "[EndDate] >= [StartDate]");

                    t.HasCheckConstraint("CK_Subscriptions_MaxUsers", "[MaxUsers] >= 1");

                    t.HasCheckConstraint("CK_Subscriptions_Price", "[Price] >= 0");
                });
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.TermsAcceptance", b =>
            {
                b.Property<int>("TermsAcceptanceId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermsAcceptanceId"));

                b.Property<DateTime>("AcceptedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("CompanyId")
                    .HasColumnType("int");

                b.Property<int>("TermsVersionId")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("TermsAcceptanceId");

                b.HasIndex("TermsVersionId");

                b.HasIndex("CompanyId", "TermsVersionId")
                    .IsUnique();

                b.ToTable("TermsAcceptances");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.TermsVersion", b =>
            {
                b.Property<int>("TermsVersionId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermsVersionId"));

                b.Property<DateTime?>("ArchivedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime?>("PublishedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("PublishedBy")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("RequiresAcceptance")
                    .HasColumnType("bit");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("VersionNumber")
                    .HasColumnType("int");

                b.HasKey("TermsVersionId");

                b.HasIndex("VersionNumber")
                    .IsUnique();

                b.ToTable("TermsVersions");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("freshcrumbs.CRM.domain.entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.ApplicationUser", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.Company", "Company")
                    .WithMany("Users")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Company");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.CompanyDatabase", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Company");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.Company", b =>
            {
                b.Navigation("Users");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.PlanFeature", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.Plan", "Plan")
                    .WithMany("Features")
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Plan");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.Plan", b =>
            {
                b.Navigation("Features");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.Subscription", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("freshcrumbs.CRM.domain.entities.Plan", "Plan")
                    .WithMany()
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("freshcrumbs.CRM.domain.entities.Subscription", "PreviousSubscription")
                    .WithMany()
                    .HasForeignKey("PreviousSubscriptionId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Company");

                b.Navigation("Plan");

                b.Navigation("PreviousSubscription");
            });

            modelBuilder.Entity("freshcrumbs.CRM.domain.entities.TermsAcceptance", b =>
            {
                b.HasOne("freshcrumbs.CRM.domain.entities.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("freshcrumbs.CRM.domain.entities.TermsVersion", "TermsVersion")
                    .WithMany()
                    .HasForeignKey("TermsVersionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Company");

                b.Navigation("TermsVersion");
            });
#pragma warning restore 612, 618
        }
    }
}