using System.Text.RegularExpressions;
using freshcrumbs.CRM.domain.entities;
using freshcrumbs.CRM.infrastructure.data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace freshcrumbs.CRM.api.Controllers
{
    [ApiController]
    [Authorize(Roles = PlatformRoles.SuperAdmin)]
    [Route("api/platform/plans")]
    public class PlansController : ControllerBase
    {
        private static readonly Regex PlanCodePattern = new("^[A-Z0-9][A-Z0-9_-]{1,29}$", RegexOptions.Compiled);

        private readonly MasterCrmDbContext _masterDb;

        public PlansController(MasterCrmDbContext masterDb)
        {
            _masterDb = masterDb;
        }

        public class PlanRequest
        {
            public string PlanCode { get; set; } = string.Empty;
            public string DisplayName { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public decimal Price { get; set; }
            public string BillingCycle { get; set; } = string.Empty;
            public List<string> Features { get; set; } = new();
            public int MaxUsers { get; set; }
            public bool BranchingEnabled { get; set; }
            public int? MaxBranches { get; set; }
        }

        [HttpGet("features")]
        public IActionResult GetFeatureCatalog()
        {
            return Ok(PlanFeatureKeys.All.Select(key => new
            {
                key,
                displayName = PlanFeatureKeys.DisplayName(key)
            }));
        }

        [HttpGet]
        public async Task<IActionResult> GetAll([FromQuery] string? status = null)
        {
            var query = _masterDb.Plans.AsNoTracking().Include(x => x.Features).AsQueryable();

            if (string.Equals(status, "Active", StringComparison.OrdinalIgnoreCase))
            {
                query = query.Where(x => x.IsActive);
            }
            else if (string.Equals(status, "Inactive", StringComparison.OrdinalIgnoreCase))
            {
                query = query.Where(x => !x.IsActive);
            }

            var plans = await query.OrderBy(x => x.DisplayName).ToListAsync();

            return Ok(plans.Select(ToResponse));
        }

        [HttpGet("{id:int}")]
        public async Task<IActionResult> GetById(int id)
        {
            var plan = await _masterDb.Plans.AsNoTracking().Include(x => x.Features)
                .FirstOrDefaultAsync(x => x.PlanId == id);

            if (plan == null)
            {
                return NotFound(new { message = $"Plan with id {id} not found." });
            }

            return Ok(ToResponse(plan));
        }

        [HttpPost]
        public async Task<IActionResult> Create(PlanRequest request)
        {
            var error = Validate(request, false, out var billingCycle, out var featureKeys);

            if (error != null)
            {
                return BadRequest(new { message = error });
            }

            var plan = new Plan
            {
                IsActive = true,
                CreatedAt = DateTime.UtcNow
            };

            Apply(plan, request, billingCycle, featureKeys);

            _masterDb.Plans.Add(plan);

            // The plan code is always generated by the system; any value sent by the client is ignored.
            for (var attempt = 0; ; attempt++)
            {
                plan.PlanCode = await GenerateNextPlanCodeAsync();

                try
                {
                    await _masterDb.SaveChangesAsync();
                    break;
                }
                catch (DbUpdateException ex) when (attempt < 4 && ex.InnerException?.Message.Contains("IX_Plans_PlanCode") == true)
                {
                }
            }

            return Created($"api/platform/plans/{plan.PlanId}", ToResponse(plan));
        }

        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, PlanRequest request)
        {
            var plan = await _masterDb.Plans.Include(x => x.Features)
                .FirstOrDefaultAsync(x => x.PlanId == id);

            if (plan == null)
            {
                return NotFound(new { message = $"Plan with id {id} not found." });
            }

            var error = Validate(request, true, out var billingCycle, out var featureKeys);

            if (error != null)
            {
                return BadRequest(new { message = error });
            }

            if (!string.Equals(request.PlanCode.Trim(), plan.PlanCode, StringComparison.OrdinalIgnoreCase))
            {
                return BadRequest(new { message = "Plan code cannot be changed after the plan is created." });
            }

            Apply(plan, request, billingCycle, featureKeys);
            plan.UpdatedAt = DateTime.UtcNow;

            await _masterDb.SaveChangesAsync();

            return Ok(ToResponse(plan));
        }

        [HttpPut("{id:int}/activate")]
        public Task<IActionResult> Activate(int id) => SetActive(id, true);

        [HttpPut("{id:int}/deactivate")]
        public Task<IActionResult> Deactivate(int id) => SetActive(id, false);

        private async Task<IActionResult> SetActive(int id, bool isActive)
        {
            var plan = await _masterDb.Plans.Include(x => x.Features)
                .FirstOrDefaultAsync(x => x.PlanId == id);

            if (plan == null)
            {
                return NotFound(new { message = $"Plan with id {id} not found." });
            }

            if (plan.IsActive != isActive)
            {
                plan.IsActive = isActive;
                plan.UpdatedAt = DateTime.UtcNow;
                await _masterDb.SaveChangesAsync();
            }

            return Ok(ToResponse(plan));
        }

        private static string? Validate(
            PlanRequest request,
            bool validateCode,
            out BillingCycle billingCycle,
            out List<string> featureKeys)
        {
            billingCycle = default;
            featureKeys = new List<string>();

            if (validateCode)
            {
                var planCode = (request.PlanCode ?? string.Empty).Trim().ToUpperInvariant();

                if (planCode.Length == 0)
                {
                    return "Plan code is required.";
                }

                if (!PlanCodePattern.IsMatch(planCode))
                {
                    return "Plan code must be 2 to 30 characters and use only letters, numbers, hyphens and underscores.";
                }
            }

            var displayName = (request.DisplayName ?? string.Empty).Trim();

            if (displayName.Length == 0)
            {
                return "Display name is required.";
            }

            if (displayName.Length > 100)
            {
                return "Display name cannot exceed 100 characters.";
            }

            if ((request.Description ?? string.Empty).Trim().Length > 500)
            {
                return "Description cannot exceed 500 characters.";
            }

            if (request.Price < 0)
            {
                return "Price cannot be negative.";
            }

            if (request.Price > 99999999.99m || decimal.Round(request.Price, 2) != request.Price)
            {
                return "Price must be at most 99,999,999.99 with no more than 2 decimal places.";
            }

            var cycleText = (request.BillingCycle ?? string.Empty).Trim();

            if (!Enum.TryParse(cycleText, true, out billingCycle)
                || !Enum.IsDefined(billingCycle)
                || int.TryParse(cycleText, out _))
            {
                return "Billing cycle must be Weekly, Monthly or Yearly.";
            }

            var requested = (request.Features ?? new List<string>())
                .Select(x => (x ?? string.Empty).Trim())
                .Where(x => x.Length > 0)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            foreach (var key in requested)
            {
                var match = PlanFeatureKeys.All.FirstOrDefault(x => string.Equals(x, key, StringComparison.OrdinalIgnoreCase));

                if (match == null)
                {
                    return $"'{key}' is not a recognized feature.";
                }

                if (match != PlanFeatureKeys.Branching)
                {
                    featureKeys.Add(match);
                }
            }

            if (featureKeys.Count == 0 && !request.BranchingEnabled)
            {
                return "Select at least one included feature.";
            }

            if (request.MaxUsers < 1 || request.MaxUsers > 100000)
            {
                return "Maximum users must be between 1 and 100,000.";
            }

            if (request.BranchingEnabled)
            {
                if (request.MaxBranches == null || request.MaxBranches < 1 || request.MaxBranches > 1000)
                {
                    return "Maximum branches must be between 1 and 1,000 when branching is enabled.";
                }
            }

            return null;
        }

        private async Task<string> GenerateNextPlanCodeAsync()
        {
            var codes = await _masterDb.Plans.AsNoTracking()
                .Where(x => x.PlanCode.StartsWith("PLN-"))
                .Select(x => x.PlanCode)
                .ToListAsync();

            var highest = codes
                .Select(code => int.TryParse(code.Substring(4), out var number) ? number : 0)
                .DefaultIfEmpty(0)
                .Max();

            return $"PLN-{highest + 1:D4}";
        }

        private static void Apply(Plan plan, PlanRequest request, BillingCycle billingCycle, List<string> featureKeys)
        {
            plan.DisplayName = request.DisplayName.Trim();
            plan.Description = (request.Description ?? string.Empty).Trim();
            plan.Price = request.Price;
            plan.BillingCycle = billingCycle;
            plan.MaxUsers = request.MaxUsers;
            plan.BranchingEnabled = request.BranchingEnabled;
            plan.MaxBranches = request.BranchingEnabled ? request.MaxBranches : null;

            var toRemove = plan.Features.Where(x => !featureKeys.Contains(x.FeatureKey)).ToList();

            foreach (var feature in toRemove)
            {
                plan.Features.Remove(feature);
            }

            foreach (var key in featureKeys)
            {
                if (!plan.Features.Any(x => x.FeatureKey == key))
                {
                    plan.Features.Add(new PlanFeature { FeatureKey = key });
                }
            }
        }

        private static object ToResponse(Plan plan)
        {
            var features = PlanFeatureKeys.All
                .Where(key => key == PlanFeatureKeys.Branching
                    ? plan.BranchingEnabled
                    : plan.Features.Any(x => x.FeatureKey == key))
                .ToList();

            return new
            {
                plan.PlanId,
                plan.PlanCode,
                plan.DisplayName,
                plan.Description,
                plan.Price,
                BillingCycle = plan.BillingCycle.ToString(),
                Features = features,
                plan.MaxUsers,
                plan.BranchingEnabled,
                plan.MaxBranches,
                plan.IsActive,
                plan.CreatedAt,
                plan.UpdatedAt
            };
        }
    }
}